config/routes.rb
Rails.application.routes.draw do
  get 'bank_accounts/index'

  get 'bank_accounts/show'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "pages#index"

  resources :bank_accounts

  namespace :api do
    namespace :v1 do
      post "bank_accounts/new_transaction", to: "bank_accounts#new_transaction"
    end
  end
end

app/models/account_transaction.rb
class AccountTransaction < ApplicationRecord
  belongs_to :bank_account
  
  before_validation :load_defaults

  TRANSACTION_TYPES = ["withdraw", "deposit"]
  
  validates :bank_account, presence: true
  validates :amount, presence: true
  validates :transaction_type, presence: true, inclusion: {in: TRANSACTION_TYPES}
  validates :transaction_no, presence: true
  validates_uniqueness_of :transaction_no

  private

  def load_defaults
    self.transaction_no = SecureRandom.uuid if self.new_record?
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bank_account.rb
class BankAccount < ApplicationRecord
  belongs_to :client
  has_many :account_transactions

  before_validation :load_defaults
  
  validates :client, presence: true
  validates :account_no, presence: true
  validates :balance, presence: true 
  validates_uniqueness_of :account_no, case_sensitive: false
  validates_numericality_of :balance

  def to_s
    account_no
  end
  
  private

  def load_defaults
    self.balance = 0.00 if self.new_record?
  end

end

app/models/client.rb
class Client < ApplicationRecord
  has_many :bank_accounts

  before_save :format_name

  validates :first_name, presence: true
  validates :middle_name, presence: true
  validates :last_name, presence: true
  validates :client_no, presence: true
  validates_uniqueness_of :client_no, case_sensitive: false

  def to_s
    "#{last_name}, #{first_name} #{middle_name}"
  end

  private

  def format_name
    self.first_name  = self.first_name.upcase unless self.first_name.nil?
    self.last_name   = self.last_name.upcase unless self.first_name.nil?
    self.middle_name = self.middle_name.upcase unless self.middle_name.nil?
  end
end

app/controllers/api/v1/bank_accounts_controller.rb
module Api
  module V1
    class BankAccountsController < ApplicationController
      def new_transaction
        amount           = params[:amount]
	transaction_type = params[:transaction_type]
	bank_account_id  = params[:bank_account_id]
	errors = ::BankAccounts::ValidateNewTransaction.new(
	           amount,
		   transaction_type,
		   bank_account_id
	         ).execute!

	if errors.size > 0
	  render json: {errors: errors}, status: 402
	else
          bank_account = ::BankAccounts::PerformTransaction.new(
		           amount,
		           transaction_type,
		           bank_account_id     
	                 ).execute!
          render json: {balance: bank_account.balance}
	end
      end 
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bank_accounts_controller.rb
class BankAccountsController < ApplicationController
  before_action :load_bank_account, only: [:show]
  
  def index
    @bank_accounts = BankAccount.all
  end

  def show; end

  def new
    @bank_account = BankAccount.new
  end

  def create
    @bank_account = BankAccount.new(bank_account_params)
   
    if @bank_account.save
      flash[:success] = "You have successfully added a new bank account"

      redirect_to bank_account_path(@bank_account.id) 
    else
      render :new
    end
  end

  def edit; end

  def update
  end

  def destroy
  end

  private

  def bank_account_params
    params.require(:bank_account).permit(:account_no, :client_id)  
  end

  def load_bank_account
    @bank_account = BankAccount.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def number_of_accounts
    BankAccount.count
  end

  def number_of_clients
    Client.count
  end
end

app/helpers/bank_accounts_helper.rb
module BankAccountsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/bank_accounts/_form.html.haml
#modal-transaction.modal.fade.modal-fade
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{type:'button', data:{dismiss:'modal'}}
          %span{aria:{hidden:'true'}}
            %i.fa.fa-close
          %span.sr-only Close
        %h4.modal-title
      .modal-body
        .row
          .col-md-12
            .notification
        .row
          .col-md-6
            %label
              Amount
            = text_field_tag :amount, 0.00, id: "amount", class: "form-control"
          .col-md-6
            %label
              Transaction Type
            = select_tag :transaction_type, options_for_select(AccountTransaction::TRANSACTION_TYPES), id: "t-type", class: "form-control"
      .modal-footer
        %button.btn.btn-default{type:'button', data:{dismiss:'modal'}} Close
        %button#btn-save.btn.btn-primary{type:'button'} Save

app/views/bank_accounts/_transaction.html.haml
%table.table.table-hovered
  %thead
    %tr
      %th Date of Transaction
      %th Transaction Type
      %th Amount
  %tbody
    - bank_account.account_transactions.each do |t|
      %tr
        %td #{time_ago_in_words(t.created_at)}
        %td #{t.transaction_type}
        %td #{number_to_currency(t.amount, unit: "P")}
    %tr
      %th
      %th Balance
      %th #{number_to_currency(bank_account.balance, unit: "P")}

app/views/bank_accounts/index.html.haml
%h2 Bank Accounts 

%table.table.table-hovered
  %thead
    %tr
      %th Account Number
      %th Balance
      %th Actions
  %tbody
    - @bank_accounts.each do |account|
      %tr
        %td #{account.account_no}
        %td #{number_to_currency(account.balance, unit: "P")}
        %td
          = link_to bank_account_path(account), class: "btn btn-primary" do
            Show

app/views/bank_accounts/new.html.haml
%h2 New Bank Account

= simple_form_for @bank_account do |f|
  = f.input :account_no, input_html: { class: "form-control" }
  = f.association :client, input_html: { class: "form-control" }
  %hr  
  = button_tag type: :submit, class: "btn btn-primary" do
    Save
  = link_to root_path, class: "btn btn-default" do
    Cancel

app/views/bank_accounts/show.html.haml
%h2 
  Account Number: #{@bank_account.account_no}
  %small
    #{@bank_account.client}

= button_tag :new_transaction, id: "btn-transaction", class: "btn btn-primary" do
  New Transaction

#parameters{ data: {bank_account_id: @bank_account.id}}
  
= render partial: 'form'
= render partial: 'transaction', locals: {bank_account: @bank_account}


= javascript_include_tag "bank_accounts/Show"
:javascript
  $(document).ready(function(){
    Show.init();
  });

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mybankapp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/index.html.haml
%h2 Bank

.row
  .col-md-12
    %h4
      Number of Accounts: #{number_of_accounts}
    %h4
      Number of Clients: #{number_of_clients}

.row
  .col-md-12
    = link_to bank_accounts_path do
      Bank Accounts
    = link_to new_bank_account_path do
      New Bank Account